name: 'Install clang'
runs:
  using: "composite"
  steps:
    - name: Install clang
      shell: bash
      run: |
        sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main"
        sudo apt-get update
        sudo apt-get install -y clang-format-18 clang-tidy-18 clang-tools-18 clang-18 lld
        sudo rm -f /usr/bin/clang
        sudo rm -f /usr/bin/clang++
        sudo rm -f /usr/bin/clang-tidy
        sudo rm -f /usr/bin/clang-format
        sudo ln -s /usr/bin/clang-18 /usr/bin/clang
        sudo ln -s /usr/bin/clang++-18 /usr/bin/clang++
        sudo ln -s /usr/bin/clang-tidy-18 /usr/bin/clang-tidy
        sudo ln -s /usr/bin/clang-format-18 /usr/bin/clang-format
