[package]
name = "iceoryx2_benchmark_nodes"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
iceoryx2 = { path = "../../../iceoryx2/iceoryx2" }
rmw_iceoryx2_benchmark_msgs = { path = "../../../../install/rmw_iceoryx2_benchmark_msgs/share/rmw_iceoryx2_benchmark_msgs/rust" }
rmw_iceoryx2_interoperability = { path = "../../rmw_iceoryx2_interoperability" }
rosidl_runtime_rs = "0.6"
