<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rmw_iceoryx2_interoperation_demo_nodes</name>
  <version>0.1.0</version>
  <description>ROS 2 nodes for the rmw_iceoryx2 / iceoryx2 interoperation demo</description>
  <maintainer email="jeff@ithier.dev">Jeff Ithier</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rmw_iceoryx2_interoperation_demo_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
